// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCloudRemote(arg1, arg2) {
  return window['go']['desktop']['Application']['CreateCloudRemote'](arg1, arg2);
}

export function DeleteCloudRemote(arg1) {
  return window['go']['desktop']['Application']['DeleteCloudRemote'](arg1);
}

export function ExecuteAction(arg1, arg2) {
  return window['go']['desktop']['Application']['ExecuteAction'](arg1, arg2);
}

export function ExecuteActionWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Application']['ExecuteActionWithOptions'](arg1, arg2, arg3, arg4);
}

export function GetSnapshot() {
  return window['go']['desktop']['Application']['GetSnapshot']();
}

export function OpenCloudLoginWizard() {
  return window['go']['desktop']['Application']['OpenCloudLoginWizard']();
}

export function OpenLocalFolder(arg1) {
  return window['go']['desktop']['Application']['OpenLocalFolder'](arg1);
}

export function SetPollingInterval(arg1) {
  return window['go']['desktop']['Application']['SetPollingInterval'](arg1);
}

export function Shutdown() {
  return window['go']['desktop']['Application']['Shutdown']();
}
