// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CreateCloudRemote(arg1:string,arg2:string):Promise<core.ActionResult>;

export function DeleteCloudRemote(arg1:string):Promise<core.ActionResult>;

export function ExecuteAction(arg1:string,arg2:string):Promise<core.ActionResult>;

export function ExecuteActionWithOptions(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<core.ActionResult>;

export function GetSnapshot():Promise<core.AppSnapshot>;

export function OpenCloudLoginWizard():Promise<void>;

export function OpenLocalFolder(arg1:string):Promise<void>;

export function SetPollingInterval(arg1:number):Promise<void>;

export function Shutdown():Promise<void>;
